language: python
dist: xenial
sudo: true

python:
  - 3.7

env:
  global:
    - PIPENV_ENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENV=1

install:
  - pip install pipenv
  - pipenv sync -d

script:
  - pipenv install flake8